<script lang="ts">
	import { onMount } from 'svelte';
	import { Boxes, UserPlus } from '@lucide/svelte';
	let users = $state<any[]>([]), workspaces = $state<any[]>([]), members = $state<any[]>([]), error = $state('');
	async function load() { const r = await fetch('/api/admin', { cache: 'no-store' }); const p = await r.json(); if (!r.ok) { error = p.error || 'Could not load workspace access'; return; } users = p.users ?? []; workspaces = p.workspaces ?? []; members = p.workspaceMembers ?? []; }
	onMount(() => { void load(); });
	async function call(action: string, body: Record<string, unknown>) { error = ''; const r = await fetch('/api/admin', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ action, ...body }) }); const p = await r.json(); if (!r.ok) { error = p.error || 'Update failed'; return; } await load(); }
	function memberRows(workspaceId: string) { return members.filter((m) => m.workspace_id === workspaceId).map((m) => ({ ...m, user: users.find((u) => u.id === m.user_id) })).filter((m) => m.user); }
	function available(workspaceId: string) { const ids = new Set(members.filter((m) => m.workspace_id === workspaceId).map((m) => m.user_id)); return users.filter((u) => !ids.has(u.id)); }
</script>
<div class="mx-auto max-w-6xl space-y-6 p-4 sm:p-6">
	<header><div class="flex items-center gap-2 text-primary"><Boxes class="size-5" /><p class="text-xs font-semibold uppercase tracking-[0.16em]">Administration</p></div><h1 class="mt-1 text-2xl font-semibold tracking-tight">Workspace members</h1><p class="mt-1 text-sm text-muted-foreground">Assign users and workspace-level roles.</p></header>
	{#if error}<div class="rounded-lg border border-destructive/40 bg-destructive/10 px-4 py-3 text-sm text-destructive">{error}</div>{/if}
	<div class="space-y-4">{#each workspaces as workspace (workspace.id)}<section class="rounded-xl border bg-card p-4 shadow-sm"><div class="flex flex-wrap items-center justify-between gap-3"><div><h2 class="font-semibold">{workspace.name}</h2><p class="text-xs text-muted-foreground">{workspace.visibility} · {workspace.status}{workspace.is_main ? ' · main workspace' : ''}</p></div>{#if available(workspace.id).length}<div class="flex items-center gap-2"><UserPlus class="size-4 text-muted-foreground" /><select class="h-9 rounded-md border border-input bg-background px-3 text-sm" onchange={(e) => { const id = e.currentTarget.value; if (id) { void call('workspace.member.save', { workspaceId: workspace.id, userId: id, role: 'viewer' }); e.currentTarget.value = ''; } }}><option value="">Add user…</option>{#each available(workspace.id) as user}<option value={user.id}>{user.display_name} (@{user.username})</option>{/each}</select></div>{/if}</div><div class="mt-4 space-y-2">{#each memberRows(workspace.id) as member}<div class="grid gap-2 rounded-lg border px-3 py-2 sm:grid-cols-[1fr_170px_auto] sm:items-center"><div class="text-sm"><span class="font-medium">{member.user.display_name}</span> <span class="text-muted-foreground">@{member.user.username}</span></div><select class="h-9 rounded-md border border-input bg-background px-3 text-sm" value={member.role} onchange={(e) => call('workspace.member.save', { workspaceId: workspace.id, userId: member.user.id, role: e.currentTarget.value })}><option value="owner">Owner</option><option value="editor">Editor</option><option value="contributor">Contributor</option><option value="viewer">Viewer</option></select><button class="rounded-md border px-3 py-2 text-xs text-destructive hover:bg-destructive/10" onclick={() => call('workspace.member.remove', { workspaceId: workspace.id, userId: member.user.id })}>Remove</button></div>{/each}{#if memberRows(workspace.id).length === 0}<p class="text-sm text-muted-foreground">No explicit members.</p>{/if}</div></section>{/each}</div>
</div>
