<script lang="ts">
	import { onMount } from 'svelte';
	import { api, ApiError } from '$lib/api';
	import { workspace } from '$lib/workspace.svelte';
	import { Badge, Button, Card, CardContent, CardDescription, CardHeader, CardTitle } from '$lib/components/ui';
	import { Plus, Save, Trash2 } from '@lucide/svelte';

	let sorter:any=$state(null),loading=$state(true),saving=$state(false),error=$state(''),notice=$state('');
	const available=$derived(workspace.workspaces.filter((item:any)=>item.permission==='owner'||item.management_permissions?.sorter_view===true));
	const currentId=()=>available.some((item:any)=>item.id===workspace.currentId)?String(workspace.currentId||''):String(available[0]?.id||'');
	const canManage=$derived(available.find((item:any)=>item.id===currentId())?.permission==='owner'||available.find((item:any)=>item.id===currentId())?.management_permissions?.sorter_manage_rules===true);
	const message=(e:unknown)=>e instanceof ApiError?e.message:e instanceof Error?e.message:'Unable to load APEX sorter settings';

	async function load(){loading=true;error='';notice='';try{if(!workspace.loaded)await workspace.load();const id=currentId();if(id&&workspace.currentId!==id)workspace.select(id);if(id){const data=await api.get<any>(`/addons/apex/workspaces/${encodeURIComponent(id)}/settings`);sorter=structuredClone(data.sorter);}}catch(e){error=message(e);}finally{loading=false;}}
	async function save(){const id=currentId();if(!id||!sorter||saving)return;saving=true;error='';notice='';try{const result=await api.patch<any>(`/addons/apex/workspaces/${encodeURIComponent(id)}/settings`,{sorter});sorter=structuredClone(result.sorter);notice='Knowledge Sorter settings saved.';}catch(e){error=message(e);}finally{saving=false;}}
	function addRule(){sorter.rules=[...(sorter.rules||[]),{id:`rule-${Date.now()}`,enabled:true,name:'New sorting rule',extensions:[],categories:[],minConfidence:sorter.minConfidence||0.75,target:'knowledge',convertTo:null}];sorter={...sorter};}
	function removeRule(index:number){sorter.rules=(sorter.rules||[]).filter((_:any,i:number)=>i!==index);sorter={...sorter};}
	function csv(value:any){return Array.isArray(value)?value.join(', '):'';}
	function setCsv(rule:any,key:string,value:string){rule[key]=value.split(',').map((item)=>item.trim()).filter(Boolean);sorter={...sorter,rules:[...(sorter.rules||[])]};}
	onMount(load);
</script>

<svelte:head><title>APEX Sorter Settings · OrbitFS</title></svelte:head>
<div class="mx-auto max-w-6xl space-y-5 p-4 md:p-6">
	<div class="flex flex-wrap items-start justify-between gap-3 border-b border-border/60 pb-4"><div><p class="text-xs font-semibold uppercase tracking-[.16em] text-primary">APEX · PANEL</p><h1 class="mt-1 text-2xl font-semibold">Knowledge Sorter Settings</h1><p class="mt-1 max-w-3xl text-sm text-muted-foreground">Workspace-level sorting behaviour, confidence, approval rules and routing preferences. Engine runtime policy is managed separately on Engine Console.</p></div><div class="flex gap-2"><a href="/sorter-converter"><Button variant="outline">APEX Unit</Button></a><Button onclick={save} disabled={!sorter||saving||!canManage}><Save class="size-4"/>{saving?'Saving…':'Save settings'}</Button></div></div>
	{#if error}<div class="rounded-md border border-destructive/30 bg-destructive/10 p-3 text-sm text-destructive">{error}</div>{/if}{#if notice}<div class="rounded-md border border-emerald-500/30 bg-emerald-500/10 p-3 text-sm">{notice}</div>{/if}
	{#if available.length===0}<Card><CardContent class="p-8 text-center text-sm text-muted-foreground">No workspace with APEX sorter access is available.</CardContent></Card>{:else}
		<Card><CardHeader><CardTitle>Workspace</CardTitle><CardDescription>Sorter settings are isolated per workspace.</CardDescription></CardHeader><CardContent class="flex flex-wrap items-center gap-3"><select class="min-w-64 rounded-md border bg-background px-3 py-2 text-sm" value={currentId()} onchange={async(e)=>{workspace.select(e.currentTarget.value);await load();}}>{#each available as item}<option value={item.id}>{item.name}</option>{/each}</select><Badge variant={canManage?'success':'secondary'}>{canManage?'Can edit':'View only'}</Badge></CardContent></Card>
		{#if sorter}
			<div class="grid gap-4 lg:grid-cols-2">
				<Card><CardHeader><CardTitle>Automation & review</CardTitle><CardDescription>How APEX should treat incoming content in this workspace.</CardDescription></CardHeader><CardContent class="space-y-3 text-sm">
					<label class="flex items-center justify-between gap-3 rounded-md border p-3"><span><b>Sorter enabled</b><small class="block text-muted-foreground">Allow APEX classification and routing.</small></span><input type="checkbox" bind:checked={sorter.enabled} disabled={!canManage}/></label>
					<label class="flex items-center justify-between gap-3 rounded-md border p-3"><span><b>Automatic analysis</b><small class="block text-muted-foreground">Analyze new APEX knowledge as it arrives.</small></span><input type="checkbox" bind:checked={sorter.automaticAnalysis} disabled={!canManage}/></label>
					<label class="flex items-center justify-between gap-3 rounded-md border p-3"><span><b>Require approval</b><small class="block text-muted-foreground">Queue routing changes before applying them.</small></span><input type="checkbox" bind:checked={sorter.requireApproval} disabled={!canManage||sorter.mode==='auto_apply'}/></label>
					<label class="flex items-center justify-between gap-3 rounded-md border p-3"><span><b>Learning</b><small class="block text-muted-foreground">Keep workspace routing preferences available to APEX.</small></span><input type="checkbox" bind:checked={sorter.learning} disabled={!canManage}/></label>
				</CardContent></Card>
				<Card><CardHeader><CardTitle>Behaviour & safety</CardTitle><CardDescription>Cloud-native replacement for the old scan/service settings.</CardDescription></CardHeader><CardContent class="space-y-3 text-sm">
					<label class="block space-y-1"><span class="font-medium">Mode</span><select class="w-full rounded-md border bg-background px-3 py-2" bind:value={sorter.mode} disabled={!canManage}><option value="preview">Preview only</option><option value="approval_queue">Approval queue</option><option value="auto_apply">Auto apply</option></select></label>
					<label class="block space-y-1"><span class="font-medium">Minimum confidence · {Math.round(Number(sorter.minConfidence||0)*100)}%</span><input class="w-full" type="range" min="0" max="1" step="0.01" bind:value={sorter.minConfidence} disabled={!canManage}/></label>
					<label class="block space-y-1"><span class="font-medium">Max items per run</span><input class="w-full rounded-md border bg-background px-3 py-2" type="number" min="1" max="1000" bind:value={sorter.maxItemsPerRun} disabled={!canManage}/></label>
					<label class="flex items-center justify-between gap-3 rounded-md border p-3"><span><b>Recursive scope</b><small class="block text-muted-foreground">Include nested Knowledge/project scopes.</small></span><input type="checkbox" bind:checked={sorter.recursive} disabled={!canManage}/></label>
				</CardContent></Card>
			</div>

			<Card><CardHeader><CardTitle>Sorter scope</CardTitle><CardDescription>Cloud scopes replace old machine filesystem watch folders.</CardDescription></CardHeader><CardContent class="grid gap-3 md:grid-cols-2"><label class="space-y-1 text-sm"><span class="font-medium">Include scopes</span><input class="w-full rounded-md border bg-background px-3 py-2" value={csv(sorter.includeScopes)} onchange={(e)=>sorter.includeScopes=e.currentTarget.value.split(',').map(x=>x.trim()).filter(Boolean)} disabled={!canManage}/><small class="text-muted-foreground">Example: library, knowledge, projects, profiles</small></label><label class="space-y-1 text-sm"><span class="font-medium">Exclude scopes</span><input class="w-full rounded-md border bg-background px-3 py-2" value={csv(sorter.excludeScopes)} onchange={(e)=>sorter.excludeScopes=e.currentTarget.value.split(',').map(x=>x.trim()).filter(Boolean)} disabled={!canManage}/><small class="text-muted-foreground">Example: archive, trash</small></label></CardContent></Card>

			<Card><CardHeader><div class="flex flex-wrap items-start justify-between gap-3"><div><CardTitle>Sorting rules</CardTitle><CardDescription>Workspace rules carried forward from the live APEX system, adapted to Library/Knowledge destinations.</CardDescription></div><Button variant="outline" onclick={addRule} disabled={!canManage}><Plus class="size-4"/>Add rule</Button></div></CardHeader><CardContent class="space-y-3">{#if !(sorter.rules?.length)}<p class="text-sm text-muted-foreground">No custom rules. APEX will use Knowledge Setup and its deterministic routing engine.</p>{/if}{#each sorter.rules||[] as rule,index}<div class="rounded-lg border p-4"><div class="mb-3 flex items-center justify-between gap-3"><label class="flex items-center gap-2 text-sm font-medium"><input type="checkbox" bind:checked={rule.enabled} disabled={!canManage}/>{rule.name||`Rule ${index+1}`}</label><Button variant="ghost" size="sm" onclick={()=>removeRule(index)} disabled={!canManage}><Trash2 class="size-4"/></Button></div><div class="grid gap-3 md:grid-cols-2 xl:grid-cols-3"><label class="space-y-1 text-sm"><span>Name</span><input class="w-full rounded-md border bg-background px-3 py-2" bind:value={rule.name} disabled={!canManage}/></label><label class="space-y-1 text-sm"><span>Extensions</span><input class="w-full rounded-md border bg-background px-3 py-2" value={csv(rule.extensions)} onchange={(e)=>setCsv(rule,'extensions',e.currentTarget.value)} placeholder="pdf, docx, md" disabled={!canManage}/></label><label class="space-y-1 text-sm"><span>Categories</span><input class="w-full rounded-md border bg-background px-3 py-2" value={csv(rule.categories)} onchange={(e)=>setCsv(rule,'categories',e.currentTarget.value)} placeholder="incident, reference" disabled={!canManage}/></label><label class="space-y-1 text-sm"><span>Target</span><select class="w-full rounded-md border bg-background px-3 py-2" bind:value={rule.target} disabled={!canManage}><option value="knowledge">Knowledge</option><option value="reference">Reference Knowledge</option><option value="project">Project Knowledge</option><option value="profile">Profile</option><option value="review">Review queue</option></select></label><label class="space-y-1 text-sm"><span>Minimum confidence</span><input class="w-full rounded-md border bg-background px-3 py-2" type="number" min="0" max="1" step="0.01" bind:value={rule.minConfidence} disabled={!canManage}/></label><label class="space-y-1 text-sm"><span>Convert to (optional)</span><input class="w-full rounded-md border bg-background px-3 py-2" bind:value={rule.convertTo} placeholder="markdown" disabled={!canManage}/></label></div></div>{/each}</CardContent></Card>
		{/if}
	{/if}
</div>
