<script lang="ts">
	import { onMount } from 'svelte';
	import { api, ApiError } from '$lib/api';
	import { workspace } from '$lib/workspace.svelte';
	import { Badge, Button, Card, CardContent, CardDescription, CardHeader, CardTitle } from '$lib/components/ui';
	import { Save } from '@lucide/svelte';

	let converter:any=$state(null),loading=$state(true),saving=$state(false),error=$state(''),notice=$state('');
	const available=$derived(workspace.workspaces.filter((item:any)=>item.permission==='owner'||item.management_permissions?.converter_view===true));
	const currentId=()=>available.some((item:any)=>item.id===workspace.currentId)?String(workspace.currentId||''):String(available[0]?.id||'');
	const canManage=$derived(available.find((item:any)=>item.id===currentId())?.permission==='owner'||available.find((item:any)=>item.id===currentId())?.management_permissions?.converter_manage_settings===true);
	const message=(e:unknown)=>e instanceof ApiError?e.message:e instanceof Error?e.message:'Unable to load APEX converter settings';
	async function load(){loading=true;error='';notice='';try{if(!workspace.loaded)await workspace.load();const id=currentId();if(id&&workspace.currentId!==id)workspace.select(id);if(id){const data=await api.get<any>(`/addons/apex/workspaces/${encodeURIComponent(id)}/settings`);converter=structuredClone(data.converter);}}catch(e){error=message(e);}finally{loading=false;}}
	async function save(){const id=currentId();if(!id||!converter||saving)return;saving=true;error='';notice='';try{const result=await api.patch<any>(`/addons/apex/workspaces/${encodeURIComponent(id)}/settings`,{converter});converter=structuredClone(result.converter);notice='Converter settings saved.';}catch(e){error=message(e);}finally{saving=false;}}
	onMount(load);
</script>

<svelte:head><title>APEX Converter Settings · OrbitFS</title></svelte:head>
<div class="mx-auto max-w-6xl space-y-5 p-4 md:p-6">
	<div class="flex flex-wrap items-start justify-between gap-3 border-b border-border/60 pb-4"><div><p class="text-xs font-semibold uppercase tracking-[.16em] text-primary">APEX · PANEL</p><h1 class="mt-1 text-2xl font-semibold">Converter Settings</h1><p class="mt-1 max-w-3xl text-sm text-muted-foreground">Normal workspace conversion preferences. Backend processor/runtime availability and repair stay on Engine Console.</p></div><div class="flex gap-2"><a href="/sorter-converter"><Button variant="outline">APEX Unit</Button></a><Button onclick={save} disabled={!converter||saving||!canManage}><Save class="size-4"/>{saving?'Saving…':'Save settings'}</Button></div></div>
	{#if error}<div class="rounded-md border border-destructive/30 bg-destructive/10 p-3 text-sm text-destructive">{error}</div>{/if}{#if notice}<div class="rounded-md border border-emerald-500/30 bg-emerald-500/10 p-3 text-sm">{notice}</div>{/if}
	{#if available.length===0}<Card><CardContent class="p-8 text-center text-sm text-muted-foreground">No workspace with APEX converter access is available.</CardContent></Card>{:else}
		<Card><CardHeader><CardTitle>Workspace</CardTitle><CardDescription>Converter preferences are isolated per workspace.</CardDescription></CardHeader><CardContent class="flex flex-wrap items-center gap-3"><select class="min-w-64 rounded-md border bg-background px-3 py-2 text-sm" value={currentId()} onchange={async(e)=>{workspace.select(e.currentTarget.value);await load();}}>{#each available as item}<option value={item.id}>{item.name}</option>{/each}</select><Badge variant={canManage?'success':'secondary'}>{canManage?'Can edit':'View only'}</Badge></CardContent></Card>
		{#if converter}
			<div class="grid gap-4 lg:grid-cols-2">
				<Card><CardHeader><CardTitle>Processing</CardTitle><CardDescription>Default behaviour for jobs started from the Panel converter.</CardDescription></CardHeader><CardContent class="space-y-3 text-sm"><label class="flex items-center justify-between gap-3 rounded-md border p-3"><span><b>Preserve source</b><small class="block text-muted-foreground">Keep the original uploaded source in OrbitFS storage.</small></span><input type="checkbox" bind:checked={converter.preserveSource} disabled={!canManage}/></label><label class="flex items-center justify-between gap-3 rounded-md border p-3"><span><b>Allow overwrite</b><small class="block text-muted-foreground">Permit a conversion target to replace an existing output when supported.</small></span><input type="checkbox" bind:checked={converter.allowOverwrite} disabled={!canManage}/></label><label class="block space-y-1"><span class="font-medium">Concurrent jobs</span><input class="w-full rounded-md border bg-background px-3 py-2" type="number" min="1" max="8" bind:value={converter.maxConcurrentJobs} disabled={!canManage}/></label><label class="block space-y-1"><span class="font-medium">Job timeout (seconds)</span><input class="w-full rounded-md border bg-background px-3 py-2" type="number" min="15" max="600" bind:value={converter.timeoutSeconds} disabled={!canManage}/></label><label class="block space-y-1"><span class="font-medium">Default Knowledge destination</span><select class="w-full rounded-md border bg-background px-3 py-2" bind:value={converter.defaultImportMode} disabled={!canManage}><option value="knowledge">Knowledge</option><option value="reference">Reference-only Knowledge</option><option value="draft">Draft Knowledge</option></select></label></CardContent></Card>
				<Card><CardHeader><CardTitle>Default output formats</CardTitle><CardDescription>Preferred formats where the active APEX processor supports that conversion family.</CardDescription></CardHeader><CardContent class="grid gap-3 sm:grid-cols-2 text-sm"><label class="space-y-1"><span>Documents</span><select class="w-full rounded-md border bg-background px-3 py-2" bind:value={converter.defaults.document} disabled={!canManage}><option value="markdown">Markdown</option><option value="txt">Text</option><option value="json">JSON</option><option value="html">HTML</option></select></label><label class="space-y-1"><span>Office</span><select class="w-full rounded-md border bg-background px-3 py-2" bind:value={converter.defaults.office} disabled={!canManage}><option value="pdf">PDF</option><option value="docx">DOCX</option><option value="html">HTML</option></select></label><label class="space-y-1"><span>Images</span><select class="w-full rounded-md border bg-background px-3 py-2" bind:value={converter.defaults.image} disabled={!canManage}><option value="png">PNG</option><option value="jpg">JPG</option><option value="webp">WebP</option></select></label><label class="space-y-1"><span>Video</span><select class="w-full rounded-md border bg-background px-3 py-2" bind:value={converter.defaults.video} disabled={!canManage}><option value="mp4">MP4</option><option value="webm">WebM</option></select></label><label class="space-y-1"><span>Audio</span><select class="w-full rounded-md border bg-background px-3 py-2" bind:value={converter.defaults.audio} disabled={!canManage}><option value="mp3">MP3</option><option value="aac">AAC</option><option value="wav">WAV</option></select></label></CardContent></Card>
			</div>

			<div class="grid gap-4 lg:grid-cols-3">
				<Card><CardHeader><CardTitle>Image</CardTitle></CardHeader><CardContent class="space-y-3 text-sm"><label class="block space-y-1"><span>Quality · {converter.image.quality}</span><input class="w-full" type="range" min="1" max="100" bind:value={converter.image.quality} disabled={!canManage}/></label><label class="flex items-center justify-between gap-3"><span>Strip metadata</span><input type="checkbox" bind:checked={converter.image.stripMetadata} disabled={!canManage}/></label></CardContent></Card>
				<Card><CardHeader><CardTitle>Video / Audio</CardTitle></CardHeader><CardContent class="space-y-3 text-sm"><label class="block space-y-1"><span>Video preset</span><select class="w-full rounded-md border bg-background px-3 py-2" bind:value={converter.video.preset} disabled={!canManage}><option value="fast">Fast</option><option value="medium">Medium</option><option value="quality">Quality</option></select></label><label class="block space-y-1"><span>Video codec</span><input class="w-full rounded-md border bg-background px-3 py-2" bind:value={converter.video.codec} disabled={!canManage}/></label><label class="block space-y-1"><span>Audio codec</span><input class="w-full rounded-md border bg-background px-3 py-2" bind:value={converter.audio.codec} disabled={!canManage}/></label><label class="block space-y-1"><span>Audio bitrate (kbps)</span><input class="w-full rounded-md border bg-background px-3 py-2" type="number" min="32" max="512" bind:value={converter.audio.bitrateKbps} disabled={!canManage}/></label></CardContent></Card>
				<Card><CardHeader><CardTitle>Office</CardTitle></CardHeader><CardContent class="text-sm"><label class="flex items-center justify-between gap-3 rounded-md border p-3"><span><b>Keep original</b><small class="block text-muted-foreground">Retain the source Office document alongside generated output.</small></span><input type="checkbox" bind:checked={converter.office.keepOriginal} disabled={!canManage}/></label></CardContent></Card>
			</div>
		{/if}
	{/if}
</div>
