import { json } from '@sveltejs/kit';
import { requireUser,requireAdmin } from '$lib/server/auth';
import { assertComponentLicensed } from '$lib/server/component-license';
import { apexPolicy,saveApexPolicy,apexWorkspaceStatus,apexAnalyze,apexQueueSuggestion,apexEngineState } from '$lib/server/apex-cloud';
import { getApexWorkspaceSettings,saveApexWorkspaceSettings } from '$lib/server/apex-workspace-settings';
const out=(e:any)=>json({error:String(e?.message||'APEX request failed'),code:String(e?.code||'APEX_ERROR')},{status:Number(e?.status||500)});
const parse=(p:string)=>{const x=String(p||'').split('/').filter(Boolean);if(x[0]==='admin')return{admin:true,area:x[1]||''};const i=x.indexOf('workspaces');return i>=0?{workspaceId:x[i+1],area:x[i+2]||'',action:x[i+3]||''}:{} as any;};
export async function GET({params,cookies}:any){try{await assertComponentLicensed('orbitfs_apex');const r:any=parse(params.path);if(r.admin){const user=await requireAdmin(cookies);if(r.area==='policy')return json({policy:await apexPolicy(user),engine:await apexEngineState()});}const user=await requireUser(cookies);if(r.workspaceId&&(!r.area||r.area==='status'))return json(await apexWorkspaceStatus(user,r.workspaceId));if(r.workspaceId&&r.area==='settings')return json(await getApexWorkspaceSettings(user,r.workspaceId));return json({error:'Not found'},{status:404});}catch(e){return out(e);}}
export async function PATCH({params,request,cookies}:any){try{await assertComponentLicensed('orbitfs_apex');const r:any=parse(params.path);if(r.admin&&r.area==='policy'){const user=await requireAdmin(cookies);return json({policy:await saveApexPolicy(user,await request.json().catch(()=>({}))),engine:await apexEngineState()});}if(r.workspaceId&&r.area==='settings'){const user=await requireUser(cookies);return json(await saveApexWorkspaceSettings(user,r.workspaceId,await request.json().catch(()=>({}))));}return json({error:'Not found'},{status:404});}catch(e){return out(e);}}
export async function POST({params,request,cookies}:any){try{await assertComponentLicensed('orbitfs_apex');const r:any=parse(params.path),user=await requireUser(cookies),body=await request.json().catch(()=>({}));if(r.workspaceId&&r.area==='analyze')return json({analysis:await apexAnalyze(user,r.workspaceId,body)});if(r.workspaceId&&r.area==='queue')return json(await apexQueueSuggestion(user,r.workspaceId,body));return json({error:'Not found'},{status:404});}catch(e){return out(e);}}
