<script lang="ts">
import { onMount } from 'svelte';
import { api,ApiError } from '$lib/api';
import { workspace } from '$lib/workspace.svelte';
import { Badge,Button,Card,CardContent,CardDescription,CardHeader,CardTitle } from '$lib/components/ui';
import { Activity,CheckCircle2,LoaderCircle,RefreshCw,Send } from '@lucide/svelte';
let runs:any[]=$state([]),selected:any=$state(null),findings:any[]=$state([]),selectedFindings:string[]=$state([]),scope=$state('workspace'),busy=$state(''),error=$state(''),notice=$state('');
const base=()=>workspace.currentId?`/addons/studio/workspaces/${encodeURIComponent(workspace.currentId)}`:'';
async function loadRuns(){if(!base())return;try{const r=await api.get<any>(`${base()}/analysis?limit=50`);runs=r.items||[];error='';if(selected){const fresh=runs.find((x:any)=>x.id===selected.id);if(fresh)selected=fresh;}}catch(e){error=e instanceof ApiError?e.message:'Unable to load Studio analysis';}}
async function open(run:any){busy='open';try{const r=await api.get<any>(`${base()}/analysis/${encodeURIComponent(run.id)}?records=1&review=1`);selected=r.analysis?.run||r.run||run;findings=r.analysis?.findings||r.findings||[];selectedFindings=findings.filter((f:any)=>['add','update','merge','link','review'].includes(f.finding_type)&&f.status==='candidate').map((f:any)=>f.id);}catch(e){error=e instanceof Error?e.message:'Unable to open analysis';}finally{busy='';}}
async function start(){busy='start';error='';notice='';try{const r=await api.post<any>(`${base()}/analysis`,{scope});await loadRuns();await open(r.analysis);notice='Analysis completed. Review the findings before sending anything to Library approval.';}catch(e){error=e instanceof Error?e.message:'Analysis failed';}finally{busy='';}}
function toggle(id:string){selectedFindings=selectedFindings.includes(id)?selectedFindings.filter(x=>x!==id):[...selectedFindings,id];}
async function submit(){if(!selected||!selectedFindings.length)return;busy='submit';try{const r=await api.post<any>(`${base()}/analysis/${encodeURIComponent(selected.id)}/proposals`,{findingIds:selectedFindings});notice=`${r.proposals?.length||0} finding(s) sent to the Base approval queue.`;await open(selected);}catch(e){error=e instanceof Error?e.message:'Could not create approval proposals';}finally{busy='';}}
const pct=(v:any)=>Math.round(Number(v||0)*100);
onMount(async()=>{if(!workspace.workspaces.length)await workspace.load();if(!workspace.currentId&&workspace.workspaces[0])workspace.select(workspace.workspaces[0].id);await loadRuns();});
</script>
<svelte:head><title>Studio Analysis · OrbitFS</title></svelte:head>
<div class="mx-auto max-w-7xl space-y-5 p-4 md:p-6">
<div class="flex flex-wrap items-start justify-between gap-3"><div><p class="text-xs font-semibold uppercase tracking-[.2em] text-primary">OrbitFS Studio</p><h1 class="flex items-center gap-2 text-xl font-semibold"><Activity class="size-5"/>Knowledge Analysis</h1><p class="max-w-3xl text-sm text-muted-foreground">Analyse Library/Memory, Profiles and Studio content for additions, updates, duplicates, links, conflicts and review candidates. Nothing authoritative is changed until approved in Base Library.</p></div><div class="flex gap-2"><select class="rounded-md border bg-background px-3 py-2 text-sm" value={workspace.currentId||''} onchange={async(e)=>{workspace.select(e.currentTarget.value);selected=null;findings=[];await loadRuns();}}>{#each workspace.workspaces as w}<option value={w.id}>{w.name}</option>{/each}</select><Button variant="outline" onclick={loadRuns}><RefreshCw class="size-4"/>Refresh</Button></div></div>
{#if error}<div class="rounded-md border border-destructive/30 bg-destructive/10 p-3 text-sm text-destructive">{error}</div>{/if}{#if notice}<div class="rounded-md border border-emerald-500/30 bg-emerald-500/10 p-3 text-sm">{notice}</div>{/if}
<Card><CardHeader><CardTitle>Run analysis</CardTitle><CardDescription>Analysis runs on demand inside Orbitconvert using Library, Profiles, Studio content and Knowledge Setup routing.</CardDescription></CardHeader><CardContent class="flex flex-col gap-3 md:flex-row md:items-end"><label class="flex-1 text-sm"><span class="mb-1 block font-medium">Scope</span><select class="w-full rounded-md border bg-background px-3 py-2" bind:value={scope}><option value="workspace">Entire accessible knowledge</option><option value="library">Library / Memory only</option><option value="profiles">Profiles only</option><option value="studio">Studio documents only</option></select></label><Button onclick={start} disabled={busy!==''}>{#if busy==='start'}<LoaderCircle class="size-4 animate-spin"/>{:else}<Activity class="size-4"/>{/if}Analyse</Button></CardContent></Card>
<div class="grid gap-4 xl:grid-cols-[22rem_minmax(0,1fr)]">
<Card><CardHeader><CardTitle>Analysis history</CardTitle></CardHeader><CardContent class="space-y-2">{#if !runs.length}<p class="text-sm text-muted-foreground">No analysis runs yet.</p>{/if}{#each runs as run}<button class="w-full rounded-md border p-3 text-left hover:bg-accent" class:border-primary={selected?.id===run.id} onclick={()=>open(run)}><div class="flex items-center justify-between gap-2"><strong>{run.scope_type||'workspace'}</strong><Badge variant={run.status==='complete'?'success':run.status==='failed'?'destructive':'secondary'}>{run.status}</Badge></div><p class="mt-1 text-xs text-muted-foreground">{run.created_at?new Date(run.created_at).toLocaleString():''}</p><p class="text-xs text-muted-foreground">{run.source_count||0} sources · {run.record_count||0} records · {run.finding_count||0} findings</p></button>{/each}</CardContent></Card>
<Card><CardHeader><CardTitle>{selected?'Review findings':'Select an analysis run'}</CardTitle><CardDescription>{selected?'Detected information is shown beside the proposed action/target. Select only the findings you want to send to approval.':'Open a completed run to inspect its findings.'}</CardDescription></CardHeader><CardContent class="space-y-3">
{#if selected}
<div class="grid gap-2 sm:grid-cols-4"><div class="rounded-md border p-3"><p class="text-xs text-muted-foreground">Status</p><b>{selected.status}</b></div><div class="rounded-md border p-3"><p class="text-xs text-muted-foreground">Sources</p><b>{selected.source_count||0}</b></div><div class="rounded-md border p-3"><p class="text-xs text-muted-foreground">Records</p><b>{selected.record_count||0}</b></div><div class="rounded-md border p-3"><p class="text-xs text-muted-foreground">Findings</p><b>{selected.finding_count||findings.length}</b></div></div>
{#if !findings.length}<p class="text-sm text-muted-foreground">No findings.</p>{/if}
{#each findings as f}
{@const review=f.proposal_json?.review||{}}
{@const source=review.source||{}}
{@const actionable=['add','update','merge','link','review'].includes(f.finding_type)}
<label class="block rounded-md border p-3" class:bg-muted={f.finding_type==='no_change'}>
<div class="flex items-start gap-3">{#if actionable}<input class="mt-1" type="checkbox" checked={selectedFindings.includes(f.id)} onchange={()=>toggle(f.id)}/>{:else}<CheckCircle2 class="mt-0.5 size-4 text-muted-foreground"/>{/if}<div class="min-w-0 flex-1"><div class="flex flex-wrap items-center gap-2"><Badge variant="outline">{f.finding_type.replaceAll('_',' ')}</Badge>{#if f.confidence!==null}<Badge variant="secondary">{pct(f.confidence)}%</Badge>{/if}<span class="text-xs text-muted-foreground">{f.target_system||'no target'}{f.target_section_id?` · ${f.target_section_id}`:''}</span></div><p class="mt-2 font-medium">{source.title||f.explanation||'Finding'}</p>{#if source.content}<div class="mt-2 rounded-md border bg-background p-2"><p class="text-[11px] font-semibold uppercase tracking-wide text-muted-foreground">Detected information</p><p class="mt-1 max-h-32 overflow-auto whitespace-pre-wrap text-xs">{String(source.content).slice(0,1500)}</p></div>{/if}<div class="mt-2 rounded-md border bg-background p-2"><p class="text-[11px] font-semibold uppercase tracking-wide text-muted-foreground">Suggestion</p><p class="mt-1 text-sm">{f.explanation||'Review this knowledge change.'}</p>{#if review.target}<p class="mt-1 text-xs text-muted-foreground">Existing target: {review.target.title||review.target.id||review.targetItemId}</p>{/if}</div></div></div>
</label>
{/each}
<div class="flex justify-end"><Button onclick={submit} disabled={busy!==''||!selectedFindings.length}><Send class="size-4"/>Send {selectedFindings.length} to approval</Button></div>
{/if}
</CardContent></Card>
</div></div>