<script lang="ts">
	import { onMount } from 'svelte';
	import { api, ApiError } from '$lib/api';
	import { fileContext } from '$lib/context.svelte';
	import { Badge, Button, Card, CardContent, CardHeader, CardTitle, Input } from '$lib/components/ui';
	import { Archive, CheckCircle2, History, LoaderCircle, Plus, RefreshCw, RotateCcw, Save, Send, Share2 } from '@lucide/svelte';

	type MainTab='create'|'view'; type DetailTab='entry'|'history'|'sharing'|'publishing';
	let active:MainTab=$state('view'), detailTab:DetailTab=$state('entry');
	let workspaces:any[]=$state([]), items:any[]=$state([]), selected:any=$state(null), profiles:any[]=$state([]), people:any[]=$state([]);
	let schema:any=$state({}), revisions:any[]=$state([]), shares:any[]=$state([]), proposals:any[]=$state([]), canSeeAll=$state(false);
	let loading=$state(true), busy=$state(''), error=$state(''), notice=$state('');
	let query=$state(''), statusFilter=$state('all'), typeFilter=$state('all'), categoryFilter=$state('all'), scope=$state('visible'), ownerFilter=$state('all');
	let title=$state(''), type=$state('general'), category=$state('general'), customCategory=$state(''), date=$state(new Date().toISOString().slice(0,10));
	let content=$state(''), tags=$state(''), profileIds:string[]=$state([]), profileTargetId=$state(''), profileSectionId=$state('records'), createOwner=$state('self');
	let shareUser=$state(''), sharePermission=$state('read');

	const base=()=>fileContext.currentId?`/addons/studio/workspaces/${encodeURIComponent(fileContext.currentId)}`:'';
	const workspace=()=>workspaces.find((item:any)=>item.id===fileContext.currentId);
	const can=(permission:string)=>workspace()?.management_permissions?.[permission]===true;
	const types=()=>schema.entryTypes||[]; const categories=()=>schema.categories||['general'];
	const meta=(item:any)=>item?.metadata_json&&typeof item.metadata_json==='object'?item.metadata_json:{};
	const personName=(id:string)=>people.find((p:any)=>String(p.userId)===String(id))?.username||id||'Unknown';
	const profileName=(id:string)=>profiles.find((p:any)=>String(p.id)===String(id))?.name||id;

	const filtered=$derived(items.filter((item:any)=>{
		if(statusFilter!=='all'&&item.status!==statusFilter)return false;
		if(typeFilter!=='all'&&item.subtype!==typeFilter)return false;
		if(categoryFilter!=='all'&&String(meta(item).category||'general')!==categoryFilter)return false;
		const q=query.trim().toLowerCase(); if(!q)return true;
		return [item.title,item.subtype,item.summary,item.content_text,meta(item).category,(item.tags||[]).join(' ')].some(v=>String(v||'').toLowerCase().includes(q));
	}));
	async function loadWorkspaces(){const r=await api.get<any>('/workspaces');workspaces=(r.workspaces||[]).filter((w:any)=>w.status==='active');if(!workspaces.some((w:any)=>w.id===fileContext.currentId)&&workspaces[0])fileContext.set(workspaces[0].id,workspaces[0].name);}
	async function loadAux(){if(!base())return;const [s,p,pe]=await Promise.all([api.get<any>(`${base()}/schema`),api.get<any>(`${base()}/profiles`).catch(()=>({items:[]})),api.get<any>(`${base()}/people`)]);schema=s;profiles=p.items||[];people=pe.items||[];canSeeAll=pe.canSeeAll===true;if(!types().includes(type))type=types()[0]||'general';if(!categories().includes(category))category=categories()[0]||'general';}
	async function load(){if(!base())return;loading=true;error='';try{const params=new URLSearchParams({limit:'100',compact:'1'});if(scope==='mine')params.set('scope','mine');if(scope==='shared')params.set('scope','shared');if(canSeeAll&&ownerFilter!=='all')params.set('ownerUserId',ownerFilter);items=(await api.get<any>(`${base()}/documents?${params}`)).items||[];}catch(e){error=e instanceof ApiError?e.message:'Unable to load Studio entries';}finally{loading=false;}}
	async function chooseWorkspace(id:string){const w=workspaces.find((x:any)=>x.id===id);if(!w)return;fileContext.set(w.id,w.name);selected=null;revisions=[];shares=[];proposals=[];ownerFilter='all';await loadAux();await load();}
	async function reloadFilters(){selected=null;await load();}
	async function loadRelated(){if(!selected)return;const id=selected.id;const [r,s,p]=await Promise.all([api.get<any>(`${base()}/documents/${id}/revisions`).catch(()=>({items:[]})),api.get<any>(`${base()}/documents/${id}/shares`).catch(()=>({items:[]})),api.get<any>(`${base()}/documents/${id}/proposals`).catch(()=>({requests:[]}))]);revisions=r.items||[];shares=s.items||[];proposals=p.requests||[];}
	async function open(item:any){busy='open';error='';try{selected=(await api.get<any>(`${base()}/documents/${item.id}`)).item;detailTab='entry';await loadRelated();}catch(e){error=e instanceof Error?e.message:'Open failed';}finally{busy='';}}
	function selectedCategory(){return String(meta(selected).category||'general');}
	function setSelectedCategory(value:string){selected.metadata_json={...meta(selected),category:value};}
	function selectedProfileTarget(){return String(meta(selected).profileTargetId||'');}
	function setSelectedProfileTarget(value:string){selected.metadata_json={...meta(selected),profileTargetId:value,profileSectionId:String(meta(selected).profileSectionId||'records')};}
	function selectedProfileSection(){return String(meta(selected).profileSectionId||'records');}
	function setSelectedProfileSection(value:string){selected.metadata_json={...meta(selected),profileSectionId:value||'records'};}
	function isProfileRecord(item:any=selected){return ['profile-record','profile_record','profile'].includes(String(item?.subtype||'').toLowerCase());}

	async function create(){if(!can('studio_create'))return;busy='create';error='';notice='';try{const finalCategory=category==='custom'?customCategory.trim():category;const owner=people.find((p:any)=>String(p.userId)===String(createOwner));const payload:any={kind:'document',type,subtype:type,title:title||'Entry',content,entryDate:date,tags:tags.split(',').map(x=>x.trim()).filter(Boolean),profileIds,profileTargetId:type==='profile-record'?profileTargetId:'',profileSectionId:type==='profile-record'?(profileSectionId||'records'):'records',category:finalCategory||'general'};if(createOwner!=='self'&&owner){payload.ownerUserId=owner.userId;payload.ownerUsername=owner.username;}const r=await api.post<any>(`${base()}/documents`,payload);title='';content='';tags='';profileIds=[];profileTargetId='';profileSectionId='records';customCategory='';selected=r.item;active='view';notice='Entry created.';await Promise.all([load(),loadRelated()]);}catch(e){error=e instanceof Error?e.message:'Create failed';}finally{busy='';}}
	async function save(){if(!selected||!can('studio_edit'))return;busy='save';error='';try{selected=(await api.patch<any>(`${base()}/documents/${selected.id}`,{title:selected.title,type:selected.subtype,subtype:selected.subtype,content:selected.content_text,summary:selected.summary,tags:selected.tags||[],profileIds:selected.profile_ids||[],profileTargetId:selectedProfileTarget(),profileSectionId:selectedProfileSection(),category:selectedCategory(),entryDate:selected.entry_date})).item;notice='Entry saved.';await Promise.all([load(),loadRelated()]);}catch(e){error=e instanceof Error?e.message:'Save failed';}finally{busy='';}}
	async function lifecycle(action:'finalize'|'archive'|'draft'){if(!selected)return;busy=action;error='';try{selected=(await api.post<any>(`${base()}/documents/${selected.id}/${action}`,{})).item;notice=action==='finalize'?'Entry finalized.':action==='archive'?'Entry archived.':'Entry returned to draft.';await Promise.all([load(),loadRelated()]);}catch(e){error=e instanceof Error?e.message:'Action failed';}finally{busy='';}}
	async function restoreRevision(no:number){if(!selected||!can('studio_edit'))return;if(!confirm(`Restore revision ${no}? A new revision will be created.`))return;busy='restore';try{selected=(await api.post<any>(`${base()}/documents/${selected.id}/restore-revision`,{revisionNo:no})).item;notice=`Revision ${no} restored.`;await Promise.all([load(),loadRelated()]);}catch(e){error=e instanceof Error?e.message:'Restore failed';}finally{busy='';}}
	async function addShare(){if(!selected||!shareUser)return;busy='share';try{await api.post<any>(`${base()}/documents/${selected.id}/shares`,{userId:shareUser,permission:sharePermission});shareUser='';notice='Sharing updated.';await loadRelated();}catch(e){error=e instanceof Error?e.message:'Share failed';}finally{busy='';}}
	async function removeShare(userId:string){if(!selected)return;busy='share';try{await api.delete<any>(`${base()}/documents/${selected.id}/shares?userId=${encodeURIComponent(userId)}`);await loadRelated();}catch(e){error=e instanceof Error?e.message:'Remove share failed';}finally{busy='';}}
	async function submitProposal(){if(!selected)return;busy='proposal';error='';try{if(selected.access?.canEdit&&can('studio_edit')){selected=(await api.patch<any>(`${base()}/documents/${selected.id}`,{title:selected.title,type:selected.subtype,subtype:selected.subtype,content:selected.content_text,summary:selected.summary,tags:selected.tags||[],profileIds:selected.profile_ids||[],profileTargetId:selectedProfileTarget(),profileSectionId:selectedProfileSection(),category:selectedCategory(),entryDate:selected.entry_date,saveLocation:selected.save_location})).item;}const r=await api.post<any>(`${base()}/documents/${selected.id}/proposals`,{});notice=r.request?.status==='needs_target'?'Submitted — Library reviewer needs to choose a target.':'Submitted for Library approval.';await Promise.all([load(),loadRelated()]);}catch(e){error=e instanceof Error?e.message:'Could not submit proposal';}finally{busy='';}}
	function proposalState(){return proposals[0]?.status||'';}
	onMount(async()=>{await loadWorkspaces();await loadAux();await load();});
</script>

<svelte:head><title>OrbitFS Studio</title></svelte:head>
<div class="mx-auto max-w-[1500px] space-y-4 p-3 sm:p-4 md:p-6">
	<div class="flex flex-col gap-3 xl:flex-row xl:items-start xl:justify-between">
		<div><p class="text-xs font-semibold uppercase tracking-[.22em] text-primary">OrbitFS Studio</p><h1 class="text-2xl font-semibold">Entries</h1><p class="max-w-3xl text-sm text-muted-foreground">Write, manage, share and publish workspace documentation. Library/Profile changes always go through Base approval.</p></div>
		<div class="flex flex-col gap-2 sm:flex-row"><select class="min-w-0 rounded-md border bg-background px-3 py-2 text-sm" value={fileContext.currentId} onchange={(e)=>chooseWorkspace(e.currentTarget.value)}>{#each workspaces as w}<option value={w.id}>{w.name}</option>{/each}</select><Button size="sm" variant="outline" onclick={load}><RefreshCw class="size-4" />Refresh</Button></div>
	</div>
	{#if error}<div class="rounded-md border border-destructive/30 bg-destructive/10 p-3 text-sm text-destructive">{error}</div>{/if}
	{#if notice}<div class="rounded-md border border-emerald-500/30 bg-emerald-500/10 p-3 text-sm">{notice}</div>{/if}
	<div class="grid grid-cols-2 gap-1 rounded-lg border bg-card p-1"><button class="rounded-md px-3 py-2 text-sm" class:bg-accent={active==='create'} class:font-medium={active==='create'} onclick={()=>active='create'}>Create Entry</button><button class="rounded-md px-3 py-2 text-sm" class:bg-accent={active==='view'} class:font-medium={active==='view'} onclick={()=>active='view'}>View Entries</button></div>

	{#if active==='create'}
	<Card><CardHeader><CardTitle>New entry</CardTitle></CardHeader><CardContent class="space-y-4">
		<div class="grid gap-3 md:grid-cols-2"><label class="space-y-1 text-sm"><span>Title</span><Input bind:value={title} placeholder="Entry title" /></label><label class="space-y-1 text-sm"><span>Entry type</span><select class="w-full rounded-md border bg-background px-3 py-2" bind:value={type}>{#each types() as option}<option value={option}>{option.replaceAll('-',' ')}</option>{/each}</select></label></div>
		<div class="grid gap-3 md:grid-cols-3"><label class="space-y-1 text-sm"><span>Date</span><Input type="date" bind:value={date} /></label><label class="space-y-1 text-sm"><span>Category</span><select class="w-full rounded-md border bg-background px-3 py-2" bind:value={category}>{#each categories() as option}<option value={option}>{option.replaceAll('-',' ')}</option>{/each}<option value="custom">Custom…</option></select></label>{#if category==='custom'}<label class="space-y-1 text-sm"><span>Custom category</span><Input bind:value={customCategory} placeholder="Category name" /></label>{:else}<label class="space-y-1 text-sm"><span>Tags</span><Input bind:value={tags} placeholder="notes, project, private" /></label>{/if}</div>
		{#if category==='custom'}<label class="space-y-1 text-sm"><span>Tags</span><Input bind:value={tags} placeholder="notes, project, private" /></label>{/if}
		{#if canSeeAll}<label class="space-y-1 text-sm"><span>Entry owner</span><select class="w-full rounded-md border bg-background px-3 py-2" bind:value={createOwner}><option value="self">Me</option>{#each people.filter((p:any)=>!p.current) as person}<option value={person.userId}>{person.username} · {person.role}</option>{/each}</select></label>{/if}
		{#if type==='profile-record'}<div class="grid gap-3 rounded-md border p-3 md:grid-cols-2"><label class="space-y-1 text-sm"><span class="font-medium">Destination profile</span><select class="w-full rounded-md border bg-background px-3 py-2" bind:value={profileTargetId}><option value="">Choose profile…</option>{#each profiles as profile}<option value={String(profile.id)}>{profile.name||profile.id}</option>{/each}</select><span class="block text-xs text-muted-foreground">This profile receives the approved record.</span></label><label class="space-y-1 text-sm"><span class="font-medium">Profile section</span><select class="w-full rounded-md border bg-background px-3 py-2" bind:value={profileSectionId}><option value="records">Records</option><option value="history">History</option><option value="background">Background / Who they are</option><option value="references">References</option><option value="private-notes">Private notes</option></select><span class="block text-xs text-muted-foreground">Defaults to Records.</span></label></div>{/if}{#if profiles.length}<div><p class="mb-1 text-sm">Linked profiles / references</p><select multiple class="min-h-32 w-full rounded-md border bg-background p-2 text-sm" bind:value={profileIds}>{#each profiles as profile}<option value={String(profile.id)}>{profile.name||profile.id}</option>{/each}</select><p class="mt-1 text-xs text-muted-foreground">Context links only; destination is selected above for Profile Records.</p></div>{/if}
		<div class="rounded-md border bg-muted/20 p-3 text-sm text-muted-foreground">Stored in Studio/Supabase. Publishing or routing into authoritative knowledge goes through the Library approval queue.</div>
		<label class="space-y-1 text-sm"><span>Content</span><textarea bind:value={content} rows="20" class="w-full rounded-md border bg-background p-3 font-mono text-sm" placeholder="Write the entry…"></textarea></label>
		<div class="flex justify-end"><Button onclick={create} disabled={busy!==''||!can('studio_create')||(type==='profile-record'&&!profileTargetId)}><Plus class="size-4" />Create entry</Button></div>
	</CardContent></Card>
	{:else}
	<div class="grid gap-4 xl:grid-cols-[22rem_minmax(0,1fr)]">
		<Card class="min-w-0"><CardHeader><CardTitle>Entries</CardTitle></CardHeader><CardContent class="space-y-3">
			<Input bind:value={query} placeholder="Search title, summary, tags…" />
			<div class="grid grid-cols-2 gap-2"><select class="rounded-md border bg-background p-2 text-sm" bind:value={scope} onchange={reloadFilters}><option value="visible">Visible</option><option value="mine">Mine</option><option value="shared">Shared</option></select>{#if canSeeAll}<select class="rounded-md border bg-background p-2 text-sm" bind:value={ownerFilter} onchange={reloadFilters}><option value="all">All users</option>{#each people as person}<option value={person.userId}>{person.username}</option>{/each}</select>{:else}<div></div>{/if}</div>
			<div class="grid grid-cols-2 gap-2"><select class="rounded-md border bg-background p-2 text-sm" bind:value={typeFilter}><option value="all">All types</option>{#each types() as option}<option value={option}>{option.replaceAll('-',' ')}</option>{/each}</select><select class="rounded-md border bg-background p-2 text-sm" bind:value={statusFilter}><option value="all">All status</option><option value="draft">Draft</option><option value="final">Final</option><option value="archived">Archived</option></select></div>
			<select class="w-full rounded-md border bg-background p-2 text-sm" bind:value={categoryFilter}><option value="all">All categories</option>{#each categories() as option}<option value={option}>{option.replaceAll('-',' ')}</option>{/each}</select>
			<div class="max-h-[68vh] space-y-2 overflow-y-auto pr-1">{#if loading}<p class="flex items-center gap-2 text-sm text-muted-foreground"><LoaderCircle class="size-4 animate-spin" />Loading…</p>{:else if !filtered.length}<p class="text-sm text-muted-foreground">No entries match.</p>{/if}{#each filtered as item}<button class="w-full rounded-md border p-3 text-left hover:bg-accent" class:border-primary={selected?.id===item.id} onclick={()=>open(item)}><div class="flex items-start justify-between gap-2"><div class="min-w-0"><strong class="break-words">{item.title}</strong><p class="mt-1 text-xs text-muted-foreground">{item.subtype} · {meta(item).category||'general'} · {item.entry_date||'No date'}</p><p class="text-xs text-muted-foreground">{personName(item.owner_user_id)}</p></div><Badge variant={item.status==='final'?'success':item.status==='archived'?'secondary':'warning'}>{item.status}</Badge></div></button>{/each}</div>
		</CardContent></Card>
		<Card class="min-w-0"><CardHeader><CardTitle>{selected?.title||'Select an entry'}</CardTitle></CardHeader><CardContent>
		{#if selected}
			<div class="mb-4 flex flex-wrap gap-2"><Badge variant="outline">{selected.subtype}</Badge><Badge variant="secondary">{selected.status}</Badge><Badge variant="outline">revision {selected.current_revision}</Badge>{#if proposalState()}<Badge variant="outline">approval: {proposalState().replaceAll('_',' ')}</Badge>{/if}<Badge variant="outline">owner: {personName(selected.owner_user_id)}</Badge></div>
			<div class="mb-4 grid grid-cols-4 gap-1 rounded-lg border bg-card p-1"><button class="rounded-md px-2 py-2 text-xs sm:text-sm" class:bg-accent={detailTab==='entry'} onclick={()=>detailTab='entry'}>Entry</button><button class="rounded-md px-2 py-2 text-xs sm:text-sm" class:bg-accent={detailTab==='history'} onclick={()=>detailTab='history'}>History</button><button class="rounded-md px-2 py-2 text-xs sm:text-sm" class:bg-accent={detailTab==='sharing'} onclick={()=>detailTab='sharing'}>Sharing</button><button class="rounded-md px-2 py-2 text-xs sm:text-sm" class:bg-accent={detailTab==='publishing'} onclick={()=>detailTab='publishing'}>Publishing</button></div>
			{#if detailTab==='entry'}
			<div class="space-y-3">
				<div class="grid gap-2 md:grid-cols-2"><Input bind:value={selected.title} disabled={!selected.access?.canEdit||!can('studio_edit')} /><select class="rounded-md border bg-background p-2 text-sm" bind:value={selected.subtype} disabled={!selected.access?.canEdit||!can('studio_edit')}>{#each types() as option}<option value={option}>{option.replaceAll('-',' ')}</option>{/each}</select></div>
				<div class="grid gap-2 md:grid-cols-2"><Input type="date" bind:value={selected.entry_date} disabled={!selected.access?.canEdit||!can('studio_edit')} /><Input value={selectedCategory()} oninput={(e)=>setSelectedCategory(e.currentTarget.value)} placeholder="Category" disabled={!selected.access?.canEdit||!can('studio_edit')} /></div>
				<Input value={(selected.tags||[]).join(', ')} oninput={(e)=>selected.tags=e.currentTarget.value.split(',').map((x)=>x.trim()).filter(Boolean)} placeholder="Tags" disabled={!selected.access?.canEdit||!can('studio_edit')} />
				{#if isProfileRecord()}<div class="grid gap-2 rounded-md border p-3 md:grid-cols-2"><label class="space-y-1 text-xs"><span class="font-medium">Destination profile</span><select class="w-full rounded-md border bg-background p-2 text-sm" value={selectedProfileTarget()} onchange={(e)=>setSelectedProfileTarget(e.currentTarget.value)} disabled={!selected.access?.canEdit||!can('studio_edit')}><option value="">Choose profile…</option>{#each profiles as profile}<option value={String(profile.id)}>{profile.name||profile.id}</option>{/each}</select></label><label class="space-y-1 text-xs"><span class="font-medium">Profile section</span><select class="w-full rounded-md border bg-background p-2 text-sm" value={selectedProfileSection()} onchange={(e)=>setSelectedProfileSection(e.currentTarget.value)} disabled={!selected.access?.canEdit||!can('studio_edit')}><option value="records">Records</option><option value="history">History</option><option value="background">Background / Who they are</option><option value="references">References</option><option value="private-notes">Private notes</option></select></label><p class="md:col-span-2 text-xs text-muted-foreground">Approved destination: {selectedProfileTarget()?`${profileName(selectedProfileTarget())} → ${selectedProfileSection()}`:'Choose a destination profile before publishing.'}</p></div>{/if}{#if profiles.length}<div><p class="mb-1 text-xs text-muted-foreground">Linked profiles / references</p><select multiple class="min-h-28 w-full rounded-md border bg-background p-2 text-sm" bind:value={selected.profile_ids} disabled={!selected.access?.canEdit||!can('studio_edit')}>{#each profiles as profile}<option value={String(profile.id)}>{profile.name||profile.id}</option>{/each}</select>{#if selected.profile_ids?.length}<p class="mt-1 text-xs text-muted-foreground">{selected.profile_ids.map(profileName).join(' · ')}</p>{/if}</div>{/if}
				<div class="rounded-md border bg-muted/20 p-3 text-xs text-muted-foreground">Cloud storage: Studio/Supabase · no filesystem path.</div>
				<textarea bind:value={selected.content_text} rows="24" class="w-full rounded-md border bg-background p-3 font-mono text-sm" disabled={!selected.access?.canEdit||!can('studio_edit')}></textarea>
				<div class="flex flex-wrap gap-2"><Button onclick={save} disabled={busy!==''||!selected.access?.canEdit||!can('studio_edit')}><Save class="size-4" />Save</Button>{#if selected.status==='draft'}<Button variant="outline" onclick={()=>lifecycle('finalize')} disabled={busy!==''||!can('studio_finalize')}><CheckCircle2 class="size-4" />Finalize</Button>{:else}<Button variant="outline" onclick={()=>lifecycle('draft')} disabled={busy!==''||!selected.access?.canEdit||!can('studio_edit')}><RotateCcw class="size-4" />Return to draft</Button>{/if}{#if selected.status!=='archived'}<Button variant="outline" onclick={()=>lifecycle('archive')} disabled={busy!==''||!can('studio_archive')}><Archive class="size-4" />Archive</Button>{/if}</div>
			</div>
			{:else if detailTab==='history'}
			<div class="space-y-2">{#if !revisions.length}<p class="text-sm text-muted-foreground">No revision history.</p>{/if}{#each revisions as revision}<div class="flex flex-col gap-2 rounded-md border p-3 sm:flex-row sm:items-center sm:justify-between"><div><p class="text-sm font-medium">Revision {revision.revision_no}</p><p class="text-xs text-muted-foreground">{revision.created_by} · {revision.created_at ? new Date(revision.created_at).toLocaleString() : ''}{revision.change_note ? ` · ${revision.change_note}` : ''}</p></div><Button size="sm" variant="outline" onclick={()=>restoreRevision(revision.revision_no)} disabled={busy!==''||!selected.access?.canEdit||!can('studio_edit')}><History class="size-4" />Restore</Button></div>{/each}</div>
			{:else if detailTab==='sharing'}
			<div class="space-y-3"><p class="text-sm text-muted-foreground">Share this entry with another member of the current workspace. Read access can view it; write access can edit it.</p>{#if selected.access?.canManageShares&&can('studio_manage_links')}<div class="grid gap-2 sm:grid-cols-[1fr_10rem_auto]"><select class="rounded-md border bg-background p-2 text-sm" bind:value={shareUser}><option value="">Choose user…</option>{#each people.filter((p:any)=>String(p.userId)!==String(selected.owner_user_id)&&!shares.some((s:any)=>String(s.user_id)===String(p.userId))) as person}<option value={person.userId}>{person.username}</option>{/each}</select><select class="rounded-md border bg-background p-2 text-sm" bind:value={sharePermission}><option value="read">Read</option><option value="write">Write</option></select><Button onclick={addShare} disabled={!shareUser||busy!==''}><Share2 class="size-4" />Share</Button></div>{/if}{#if !shares.length}<p class="text-sm text-muted-foreground">Private to owner/workspace managers.</p>{/if}{#each shares as share}<div class="flex items-center justify-between gap-3 rounded-md border p-3"><div><p class="text-sm font-medium">{personName(share.user_id)}</p><p class="text-xs text-muted-foreground">{share.permission} access</p></div>{#if selected.access?.canManageShares&&can('studio_manage_links')}<Button size="sm" variant="outline" onclick={()=>removeShare(share.user_id)} disabled={busy!==''}>Remove</Button>{/if}</div>{/each}</div>
			{:else}
			<div class="space-y-3"><div class="rounded-md border p-3"><p class="font-medium">Publish through Base Library</p><p class="mt-1 text-sm text-muted-foreground">Studio never writes authoritative Library/Profile knowledge directly. This creates a reviewable change request with an exact target and audit trail.</p>{#if isProfileRecord()}<div class="mt-3 rounded-md border bg-muted/30 p-3 text-sm"><p class="text-xs font-medium uppercase tracking-wide text-muted-foreground">Profile Record destination</p>{#if selectedProfileTarget()}<p class="mt-1 font-medium">{profileName(selectedProfileTarget())} → {selectedProfileSection()}</p><p class="text-xs text-muted-foreground">Approval operation: Profile Record Add</p>{:else}<p class="mt-1 text-amber-600 dark:text-amber-400">No destination profile selected. Return to Entry and choose one before publishing.</p>{/if}</div>{/if}<Button class="mt-3" variant="outline" onclick={submitProposal} disabled={busy!==''||!can('studio_finalize')||(isProfileRecord()&&!selectedProfileTarget())||['pending','needs_target','approved','applying'].includes(proposalState())}><Send class="size-4" />{['denied','changes_requested'].includes(proposalState())?'Resubmit revised entry':'Submit for approval'}</Button></div>{#if !proposals.length}<p class="text-sm text-muted-foreground">No approval requests yet.</p>{/if}{#each proposals as proposal}<div class="rounded-md border p-3" class:border-amber-500={['denied','changes_requested'].includes(proposal.status)}><div class="flex flex-wrap items-center justify-between gap-2"><p class="font-medium">{proposal.summary||'Studio publication request'}</p><Badge variant="outline">{String(proposal.status||'unknown').replaceAll('_',' ')}</Badge></div><p class="mt-1 text-xs text-muted-foreground">{proposal.submittedAt ? new Date(proposal.submittedAt).toLocaleString() : ''}{proposal.error ? ` · ${proposal.error}` : ''}</p>{#if proposal.reviewNote}<div class="mt-2 rounded-md border border-amber-500/30 bg-amber-500/10 p-2 text-sm"><strong>{proposal.status==='denied'?'Denied / returned':proposal.status==='changes_requested'?'Changes requested':'Reviewer note'}:</strong> {proposal.reviewNote}</div>{/if}{#if ['denied','changes_requested'].includes(proposal.status)}<p class="mt-2 text-xs text-muted-foreground">Edit the entry under Entry, save it, then resubmit the revised version for a new review.</p>{/if}</div>{/each}</div>
			{/if}
		{:else}<p class="text-sm text-muted-foreground">Choose an entry to open the full Studio workbench.</p>{/if}
		</CardContent></Card>
	</div>
	{/if}
</div>
