<script lang="ts">
	import { onMount } from 'svelte';
	import { goto } from '$app/navigation';
	import { api, ApiError } from '$lib/api';
	import { workspace } from '$lib/workspace.svelte';
	import { Badge, Button, Card, CardContent, CardDescription, CardHeader, CardTitle, Input } from '$lib/components/ui';
	import { BrainCircuit, Database, Plus, RotateCcw, Save, Trash2 } from '@lucide/svelte';

	type LibraryItem={id:string;name:string;kind:string;category?:string;source?:{provider?:string};lifecycleState?:string;roles?:string[]};
	type Collection={id:string;name:string};
	type KnowledgeItem={id:string;itemId:string;name:string;kind:string;category:string;provider:string;projectId:string|null;usage:'primary'|'reference';state:'active'|'final'|'draft'|'superseded'|'archive';protection:'editable'|'permission'|'locked';scope:'workspace'|'project'|'shared';priority:number};
	type Route={id:string;label:string;destinationType:'category'|'collection'|'knowledge';destinationId:string;destinationLabel:string;routing:'automatic'|'suggest'|'manual'|'never'};
	type Project={id:string;name:string;description:string;scope:'project'|'shared';routes:Route[]};

	const categories=['Core','Reference','Current','Source Material','Communication','Timeline / History','Records / Notes','Documentation','Research','Planning','Archive','Custom'];
	let loading=$state(true),saving=$state(false),error=$state(''),notice=$state(''),step=$state(1),revision=$state(0);
	let workspaceId=$state(''),libraryItems:LibraryItem[]=$state([]),collections:Collection[]=$state([]),items:KnowledgeItem[]=$state([]),projects:Project[]=$state([]),globalRoutes:Route[]=$state([]),health:any=$state(null);
	let search=$state(''),newProject=$state({name:'',description:'',scope:'project' as Project['scope']});
	let globalRouteDraft=$state({label:'',destinationType:'category' as Route['destinationType'],destinationId:'',routing:'suggest' as Route['routing']});
	let projectRouteDrafts=$state<Record<string,{label:string;destinationType:Route['destinationType'];destinationId:string;routing:Route['routing']}>>({});

	const eligible=$derived(libraryItems.filter((item)=>['library.native','memory.knowledge','base.profiles'].includes(String(item.source?.provider||''))));
	const filtered=$derived(eligible.filter((item)=>!search.trim()||`${item.name} ${item.category||''}`.toLowerCase().includes(search.toLowerCase())));
	const selectedIds=$derived(new Set(items.map((item)=>item.itemId)));
	const stepNames=['Knowledge','Projects','Routing','Review'];	function currentWorkspaceId(){return workspaceId||workspace.currentId||workspace.current?.id||'';}
	function msg(err:unknown,fallback:string){return err instanceof ApiError?err.message:err instanceof Error?err.message:fallback;}
	function providerName(provider:string){return provider==='base.profiles'?'Profile':provider==='memory.knowledge'?'Memory':'Library';}
	function destinationOptions(type:Route['destinationType']){
		if(type==='collection')return collections.map((entry)=>({id:entry.id,label:entry.name}));
		if(type==='knowledge')return eligible.map((entry)=>({id:entry.id,label:entry.name}));
		const values=[...new Set([...categories,...eligible.map((entry)=>entry.category||'').filter(Boolean)])];
		return values.map((value)=>({id:value,label:value}));
	}
	function destinationLabel(type:Route['destinationType'],id:string){return destinationOptions(type).find((entry)=>entry.id===id)?.label||id;}
	function projectDraft(projectId:string){return projectRouteDrafts[projectId]||{label:'',destinationType:'category' as Route['destinationType'],destinationId:'',routing:'suggest' as Route['routing']};}
	function asDestinationType(value:string):Route['destinationType']{return ['collection','knowledge'].includes(value)?value as Route['destinationType']:'category';}
	function asRouting(value:string):Route['routing']{return ['automatic','manual','never'].includes(value)?value as Route['routing']:'suggest';}
	function mapExisting(entry:any):KnowledgeItem{return {id:String(entry.id||crypto.randomUUID()),itemId:String(entry.itemId||entry.libraryItemId||''),name:String(entry.name||'Knowledge item'),kind:String(entry.kind||'knowledge'),category:String(entry.category||''),provider:String(entry.provider||''),projectId:entry.projectId||null,usage:entry.usage==='reference'?'reference':'primary',state:['active','final','draft','superseded','archive'].includes(entry.state)?entry.state:'active',protection:['editable','permission','locked'].includes(entry.protection)?entry.protection:'permission',scope:['workspace','project','shared'].includes(entry.scope)?entry.scope:(entry.projectId?'project':'workspace'),priority:Number(entry.priority??50)};}
	function toggleItem(source:LibraryItem,checked:boolean){
		if(!checked){items=items.filter((entry)=>entry.itemId!==source.id);return;}
		if(selectedIds.has(source.id))return;
		items=[...items,{id:crypto.randomUUID(),itemId:source.id,name:source.name,kind:source.kind||'knowledge',category:source.category||'Current',provider:String(source.source?.provider||'library.native'),projectId:null,usage:'primary',state:'active',protection:'permission',scope:'workspace',priority:50}];
	}
	function removeProject(id:string){projects=projects.filter((project)=>project.id!==id);items=items.map((item)=>item.projectId===id?{...item,projectId:null,scope:'workspace'}:item);}
	function addProject(){if(!newProject.name.trim())return;const id=crypto.randomUUID();projects=[...projects,{id,name:newProject.name.trim(),description:newProject.description.trim(),scope:newProject.scope,routes:[]}];projectRouteDrafts={...projectRouteDrafts,[id]:{label:'',destinationType:'category',destinationId:'',routing:'suggest'}};newProject={name:'',description:'',scope:'project'};}
	function addRoute(projectId?:string){
		const draft=projectId?projectRouteDrafts[projectId]:globalRouteDraft;if(!draft?.label.trim()||!draft.destinationId)return;
		const route:Route={id:crypto.randomUUID(),label:draft.label.trim(),destinationType:draft.destinationType,destinationId:draft.destinationId,destinationLabel:destinationLabel(draft.destinationType,draft.destinationId),routing:draft.routing};
		if(projectId){projects=projects.map((project)=>project.id===projectId?{...project,routes:[...project.routes,route]}:project);projectRouteDrafts={...projectRouteDrafts,[projectId]:{label:'',destinationType:'category',destinationId:'',routing:'suggest'}};}
		else{globalRoutes=[...globalRoutes,route];globalRouteDraft={label:'',destinationType:'category',destinationId:'',routing:'suggest'};}
	}	async function load(){
		loading=true;error='';
		try{
			if(!workspace.loaded)await workspace.load();
			const requested=new URLSearchParams(window.location.search).get('workspace')||'';workspaceId=requested||workspace.currentId||'';
			if(workspaceId&&workspace.currentId!==workspaceId&&workspace.workspaces.some((entry)=>entry.id===workspaceId))workspace.select(workspaceId);
			const [library,architectureResult,healthResult]=await Promise.all([
				api.get<any>(`/library/workspaces/${encodeURIComponent(workspaceId)}`),
				api.get<any>(`/workspaces/${encodeURIComponent(workspaceId)}/knowledge-architecture`),
				api.get<any>(`/workspaces/${encodeURIComponent(workspaceId)}/knowledge-architecture/health`).catch(()=>null)
			]);
			libraryItems=library.items||[];collections=library.collections||[];const architecture=architectureResult.architecture||{};
			items=[...(architecture.globalItems||[]),...(architecture.projectItems||[])].map(mapExisting);projects=architecture.projects||[];globalRoutes=architecture.globalRoutes||[];revision=Number(architecture.revision||0);health=healthResult;
			projectRouteDrafts=Object.fromEntries(projects.map((project)=>[project.id,{label:'',destinationType:'category',destinationId:'',routing:'suggest'}]));
		}catch(err){error=msg(err,'Could not load Knowledge Setup');}finally{loading=false;}
	}
	async function save(){
		saving=true;error='';notice='';
		try{
			const result=await api.put<any>(`/workspaces/${encodeURIComponent(currentWorkspaceId())}/knowledge-architecture`,{setupComplete:true,items,projects,globalRoutes});
			revision=Number(result.architecture?.revision||revision+1);items=[...(result.architecture?.globalItems||[]),...(result.architecture?.projectItems||[])].map(mapExisting);
			health=await api.get<any>(`/workspaces/${encodeURIComponent(currentWorkspaceId())}/knowledge-architecture/health`).catch(()=>health);
			notice=`Knowledge Setup saved · revision ${revision} · ${Number(result.librarySync?.selected||items.length)} Library/Profile items mapped`;
		}catch(err){error=msg(err,'Could not save Knowledge Setup');}finally{saving=false;}
	}
	onMount(load);
</script>

<svelte:head><title>Knowledge Setup · OrbitFS</title></svelte:head>
<div class="mx-auto max-w-7xl space-y-4 p-3 sm:p-4 md:p-6">
	<div class="flex flex-wrap items-start justify-between gap-3"><div><h1 class="flex items-center gap-2 text-xl font-semibold"><BrainCircuit class="size-5"/>Workspace Knowledge Setup</h1><p class="text-sm text-muted-foreground">Define how canonical Library knowledge and Profiles are organised for this workspace.</p></div><div class="flex gap-2"><Button variant="outline" onclick={()=>goto(`/workspaces?workspace=${encodeURIComponent(currentWorkspaceId())}`)}>Back</Button><Button variant="outline" onclick={load}><RotateCcw class="size-4"/>Refresh</Button></div></div>
	<Card><CardContent class="flex flex-wrap items-center justify-between gap-3 p-3"><div><div class="text-sm font-medium">{workspace.current?.name||'Current workspace'}</div><div class="text-xs text-muted-foreground">Canonical knowledge lives in Supabase Library/Memory. General workspace files remain separate from this architecture.</div></div><div class="flex flex-wrap gap-1.5"><Badge variant="secondary"><Database class="mr-1 size-3"/>Library-native</Badge><Badge variant="secondary">Schema 3</Badge><Badge variant="outline">MCP loading: OSS/CCS</Badge></div></CardContent></Card>	{#if error}<div class="rounded-md border border-destructive/30 bg-destructive/10 p-3 text-sm text-destructive">{error}</div>{/if}
	{#if notice}<div class="rounded-md border border-emerald-500/30 bg-emerald-500/10 p-3 text-sm">{notice}</div>{/if}
	{#if loading}<Card><CardContent class="p-8 text-center text-sm text-muted-foreground">Loading Library knowledge and workspace architecture…</CardContent></Card>{:else}
		<div class="grid grid-cols-4 gap-1 rounded-lg border p-1 text-xs">{#each stepNames as name,index}<button class="rounded-md px-2 py-2 {step===index+1?'bg-accent font-medium':'text-muted-foreground'}" onclick={()=>step=index+1}>{name}</button>{/each}</div>
		{#if step===1}
			<div class="grid gap-4 lg:grid-cols-[minmax(300px,.85fr)_minmax(0,1.15fr)]">
				<Card><CardHeader><CardTitle>Canonical knowledge</CardTitle><CardDescription>Choose existing Library/Memory knowledge and Profiles. Files are not registered here.</CardDescription></CardHeader><CardContent class="space-y-3"><Input placeholder="Search Library and Profiles…" bind:value={search}/><div class="max-h-[60vh] space-y-1 overflow-auto rounded-md border p-2">{#each filtered as source}<label class="flex items-center gap-2 rounded px-2 py-2 text-xs hover:bg-muted/40"><input type="checkbox" checked={selectedIds.has(source.id)} onchange={(event)=>toggleItem(source,event.currentTarget.checked)}/><span class="min-w-0 flex-1"><strong class="block truncate">{source.name}</strong><span class="text-muted-foreground">{providerName(String(source.source?.provider||''))}{source.category?` · ${source.category}`:''}</span></span></label>{/each}{#if !filtered.length}<div class="p-6 text-center text-xs text-muted-foreground">No native Library/Profile knowledge found.</div>{/if}</div></CardContent></Card>
				<Card><CardHeader><CardTitle>Knowledge rules</CardTitle><CardDescription>Primary/reference affects how consumers rank knowledge. Lifecycle and protection define authority.</CardDescription></CardHeader><CardContent class="space-y-2">{#each items as item}<div class="space-y-2 rounded-md border p-3"><div class="flex items-start justify-between gap-2"><div class="min-w-0"><strong class="block truncate text-sm">{item.name}</strong><span class="text-xs text-muted-foreground">{providerName(item.provider)} · {item.itemId}</span></div><Button size="icon" variant="ghost" onclick={()=>items=items.filter((entry)=>entry.id!==item.id)}><Trash2 class="size-4"/></Button></div>
					<div class="grid gap-2 sm:grid-cols-2 lg:grid-cols-3"><select class="h-9 rounded-md border bg-background px-2 text-xs" bind:value={item.usage}><option value="primary">Primary</option><option value="reference">Reference</option></select><select class="h-9 rounded-md border bg-background px-2 text-xs" bind:value={item.state}><option value="active">Active</option><option value="final">Final</option><option value="draft">Draft</option><option value="superseded">Superseded</option><option value="archive">Archive</option></select><select class="h-9 rounded-md border bg-background px-2 text-xs" bind:value={item.protection}><option value="editable">Editable</option><option value="permission">Permission controlled</option><option value="locked">Locked</option></select><select class="h-9 rounded-md border bg-background px-2 text-xs" bind:value={item.category}>{#each categories as category}<option value={category}>{category}</option>{/each}</select><select class="h-9 rounded-md border bg-background px-2 text-xs" bind:value={item.projectId} onchange={()=>item.scope=item.projectId?'project':'workspace'}><option value={null}>Workspace-wide</option>{#each projects as project}<option value={project.id}>{project.name}</option>{/each}</select><Input type="number" min="0" max="100" bind:value={item.priority}/></div>
				</div>{/each}{#if !items.length}<div class="rounded-md border border-dashed p-6 text-center text-sm text-muted-foreground">Select knowledge from the Library to begin.</div>{/if}</CardContent></Card>
			</div>
			<div class="flex justify-end"><Button onclick={()=>step=2}>Projects</Button></div>		{:else if step===2}
			<div class="space-y-4"><Card><CardHeader><CardTitle>Logical projects</CardTitle><CardDescription>Projects group knowledge by purpose or matter. They are not folders.</CardDescription></CardHeader><CardContent class="space-y-3"><div class="grid gap-2 md:grid-cols-[1fr_1.5fr_9rem_auto]"><Input placeholder="Project name" bind:value={newProject.name}/><Input placeholder="Description" bind:value={newProject.description}/><select class="h-10 rounded-md border bg-background px-2 text-sm" bind:value={newProject.scope}><option value="project">Project</option><option value="shared">Shared</option></select><Button onclick={addProject} disabled={!newProject.name.trim()}><Plus class="size-4"/>Add</Button></div></CardContent></Card>
			{#each projects as project}<Card><CardHeader><div class="flex items-start justify-between gap-3"><div><CardTitle>{project.name}</CardTitle><CardDescription>{project.description||'No description'} · {project.scope}</CardDescription></div><Button size="icon" variant="ghost" onclick={()=>removeProject(project.id)}><Trash2 class="size-4"/></Button></div></CardHeader><CardContent><div class="text-sm">{items.filter((item)=>item.projectId===project.id).length} mapped knowledge item(s)</div></CardContent></Card>{/each}
			</div><div class="flex justify-between"><Button variant="outline" onclick={()=>step=1}>Back</Button><Button onclick={()=>step=3}>Routing</Button></div>
		{:else if step===3}
			<div class="space-y-4"><Card><CardHeader><CardTitle>Workspace routing</CardTitle><CardDescription>Map content labels to Library categories, collections or exact knowledge targets. Consumers can use these deterministic rules before fallback behaviour.</CardDescription></CardHeader><CardContent class="space-y-3"><div class="grid gap-2 lg:grid-cols-[1fr_9rem_1.2fr_8rem_auto]"><Input placeholder="Content label, e.g. court evidence" bind:value={globalRouteDraft.label}/><select class="h-10 rounded-md border bg-background px-2 text-sm" bind:value={globalRouteDraft.destinationType} onchange={()=>globalRouteDraft.destinationId=''}><option value="category">Category</option><option value="collection">Collection</option><option value="knowledge">Knowledge item</option></select><select class="h-10 rounded-md border bg-background px-2 text-sm" bind:value={globalRouteDraft.destinationId}><option value="">Choose destination</option>{#each destinationOptions(globalRouteDraft.destinationType) as target}<option value={target.id}>{target.label}</option>{/each}</select><select class="h-10 rounded-md border bg-background px-2 text-sm" bind:value={globalRouteDraft.routing}><option value="automatic">Automatic</option><option value="suggest">Suggest</option><option value="manual">Manual</option><option value="never">Never</option></select><Button onclick={()=>addRoute()}>Add</Button></div>
			{#each globalRoutes as route}<div class="grid gap-2 rounded-md border p-2 text-xs sm:grid-cols-[1fr_1fr_1fr_auto]"><strong>{route.label}</strong><span>{route.destinationType}: {route.destinationLabel}</span><Badge variant="outline">{route.routing}</Badge><Button size="icon" variant="ghost" onclick={()=>globalRoutes=globalRoutes.filter((entry)=>entry.id!==route.id)}><Trash2 class="size-4"/></Button></div>{/each}</CardContent></Card>			{#each projects as project}{@const draft=projectDraft(project.id)}<Card><CardHeader><CardTitle>{project.name} routing</CardTitle><CardDescription>Project-specific routes override workspace routes when they match.</CardDescription></CardHeader><CardContent class="space-y-3"><div class="grid gap-2 lg:grid-cols-[1fr_9rem_1.2fr_8rem_auto]"><Input placeholder="Content label" value={draft.label} oninput={(event)=>projectRouteDrafts={...projectRouteDrafts,[project.id]:{...draft,label:event.currentTarget.value}}}/><select class="h-10 rounded-md border bg-background px-2 text-sm" value={draft.destinationType} onchange={(event)=>projectRouteDrafts={...projectRouteDrafts,[project.id]:{...draft,destinationType:asDestinationType(event.currentTarget.value),destinationId:''}}}><option value="category">Category</option><option value="collection">Collection</option><option value="knowledge">Knowledge item</option></select><select class="h-10 rounded-md border bg-background px-2 text-sm" value={draft.destinationId} onchange={(event)=>projectRouteDrafts={...projectRouteDrafts,[project.id]:{...draft,destinationId:event.currentTarget.value}}}><option value="">Choose destination</option>{#each destinationOptions(draft.destinationType) as target}<option value={target.id}>{target.label}</option>{/each}</select><select class="h-10 rounded-md border bg-background px-2 text-sm" value={draft.routing} onchange={(event)=>projectRouteDrafts={...projectRouteDrafts,[project.id]:{...draft,routing:asRouting(event.currentTarget.value)}}}><option value="automatic">Automatic</option><option value="suggest">Suggest</option><option value="manual">Manual</option><option value="never">Never</option></select><Button onclick={()=>addRoute(project.id)}>Add</Button></div>
			{#each project.routes as route}<div class="grid gap-2 rounded-md border p-2 text-xs sm:grid-cols-[1fr_1fr_1fr_auto]"><strong>{route.label}</strong><span>{route.destinationType}: {route.destinationLabel}</span><Badge variant="outline">{route.routing}</Badge><Button size="icon" variant="ghost" onclick={()=>projects=projects.map((entry)=>entry.id===project.id?{...entry,routes:entry.routes.filter((candidate)=>candidate.id!==route.id)}:entry)}><Trash2 class="size-4"/></Button></div>{/each}</CardContent></Card>{/each}
			</div><div class="flex justify-between"><Button variant="outline" onclick={()=>step=2}>Back</Button><Button onclick={()=>step=4}>Review</Button></div>
		{:else}
			<div class="grid gap-4 xl:grid-cols-[minmax(0,1.2fr)_minmax(300px,.8fr)]"><Card><CardHeader><CardTitle>Knowledge architecture</CardTitle><CardDescription>Knowledge Setup stores organisation and routing only. MCP OSS/CCS decides future startup loading.</CardDescription></CardHeader><CardContent class="space-y-4"><div><div class="mb-2 text-xs font-semibold uppercase text-muted-foreground">Mapped knowledge</div>{#each items as item}<div class="mb-1 rounded-md border p-2 text-xs"><strong>{item.name}</strong><span class="text-muted-foreground"> · {item.category} · {item.usage} · {item.state} · {item.protection} · priority {item.priority}{item.projectId?` · ${projects.find((project)=>project.id===item.projectId)?.name||'project'}`:' · workspace'}</span></div>{/each}</div><div><div class="mb-2 text-xs font-semibold uppercase text-muted-foreground">Routing</div><p class="text-xs text-muted-foreground">Decision order: explicit item policy → project route → workspace route → consumer fallback.</p><div class="mt-2 text-xs">{globalRoutes.length} workspace route(s) · {projects.reduce((sum,project)=>sum+project.routes.length,0)} project route(s)</div></div></CardContent></Card>				<Card><CardHeader><CardTitle>System health</CardTitle><CardDescription>Cloud-native knowledge dependencies for this workspace.</CardDescription></CardHeader><CardContent class="space-y-3 text-xs"><div class="flex justify-between rounded-md border p-2"><span>Library mapping</span><Badge variant={health?.library?.ok?'success':'destructive'}>{health?.library?.ok?'Healthy':'Check'}</Badge></div><div class="flex justify-between rounded-md border p-2"><span>Profiles</span><Badge variant="outline">{health?.profiles?.count??0}</Badge></div><div class="flex justify-between rounded-md border p-2"><span>Studio</span><Badge variant="outline">Serverless · {health?.studio?.count??0} items</Badge></div><div class="flex justify-between rounded-md border p-2"><span>MCP relationship</span><Badge variant="outline">OSS / CCS owns loading</Badge></div><div class="flex justify-between rounded-md border p-2"><span>Canonical filesystem</span><Badge>Disabled</Badge></div>{#if health?.library?.missing?.length}<div class="rounded-md border border-destructive/30 p-2 text-destructive">{health.library.missing.length} mapped knowledge item(s) no longer exist.</div>{/if}<Button class="w-full" onclick={save} disabled={saving}><Save class="size-4"/>{saving?'Saving…':revision?'Save changes':'Finish setup'}</Button>{#if revision}<p class="text-center text-muted-foreground">Saved revision {revision}</p>{/if}</CardContent></Card></div>
			<div><Button variant="outline" onclick={()=>step=3}>Back</Button></div>
		{/if}
	{/if}
</div>
