<script lang="ts">
import { onMount } from 'svelte';
import { api,ApiError } from '$lib/api';
import { Button,Card,CardContent,CardDescription,CardHeader,CardTitle,Input } from '$lib/components/ui';
import { ExternalLink,Save,Settings2,Gauge } from '@lucide/svelte';
let settings:any=$state(null),storage:any=$state(null),busy=$state(false),error=$state(''),notice=$state('');
const mb=(v:any)=>Math.round(Number(v||0)/10485.76)/100;
async function load(){try{const r=await api.get<any>('/addons/studio/admin/settings');settings=r.settings;storage=r.storageUsage;error='';}catch(e){error=e instanceof ApiError?e.message:'Unable to load Studio settings';}}
async function save(){busy=true;try{const r=await api.patch<any>('/addons/studio/admin/settings',{provisionExisting:settings.provisionExisting,maxJournalBytes:settings.maxJournalBytes,maxDocumentBytes:settings.maxDocumentBytes,maxSessionBytes:settings.maxSessionBytes,maxImportBytes:settings.maxImportBytes,maxExportBytes:settings.maxExportBytes});settings=r.settings;storage=r.storageUsage;notice='Studio system settings saved.';error='';}catch(e){error=e instanceof Error?e.message:'Save failed';}finally{busy=false;}}
onMount(load);
</script>
<svelte:head><title>Studio System Settings · OrbitFS</title></svelte:head>
<div class="mx-auto max-w-5xl space-y-5 p-4 md:p-6">
<div class="flex flex-wrap items-start justify-between gap-3"><div><p class="text-xs font-semibold uppercase tracking-[.2em] text-primary">OrbitFS Studio · Panel</p><h1 class="flex items-center gap-2 text-xl font-semibold"><Settings2 class="size-5"/>System Settings</h1><p class="text-sm text-muted-foreground">Panel-owned Studio provisioning, storage limits and data controls. Deep processing/runtime configuration is managed by Engine Host.</p></div><a class="inline-flex items-center gap-2 rounded-md border px-3 py-2 text-sm hover:bg-accent" href="https://orbitfsengine.vercel.app/engines/studio/configuration" target="_blank" rel="noreferrer"><Gauge class="size-4"/>Engine configuration<ExternalLink class="size-3"/></a></div>
{#if error}<div class="rounded-md border border-destructive/30 bg-destructive/10 p-3 text-sm text-destructive">{error}</div>{/if}{#if notice}<div class="rounded-md border border-emerald-500/30 bg-emerald-500/10 p-3 text-sm">{notice}</div>{/if}
{#if settings}<Card><CardHeader><CardTitle>Storage & limits</CardTitle><CardDescription>Backend-enforced Studio limits in OrbitFS Panel. Content is stored in Supabase; there is no persistent server filesystem path.</CardDescription></CardHeader><CardContent class="space-y-4"><label class="flex items-center justify-between gap-3 rounded-md border p-3"><span><b>Provision existing workspace members</b><small class="block text-muted-foreground">Provision Studio access for existing members.</small></span><input type="checkbox" bind:checked={settings.provisionExisting}/></label><div class="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{#each [['Journal','maxJournalBytes'],['Document','maxDocumentBytes'],['Session','maxSessionBytes'],['Import','maxImportBytes'],['Export','maxExportBytes']] as row}<div><span class="text-sm font-medium">{row[0]} max bytes</span><Input type="number" bind:value={settings[row[1]]}/><p class="text-xs text-muted-foreground">{mb(settings[row[1]])} MB</p></div>{/each}</div>{#if storage}<div class="rounded-md border p-3 text-sm"><b>Studio content:</b> {mb(storage.totalBytes||storage.bytes||0)} MB · Supabase</div>{/if}<div class="flex justify-end"><Button onclick={save} disabled={busy}><Save class="size-4"/>Save settings</Button></div></CardContent></Card>{/if}
</div>